openapi: 3.0.3
info:
  title: Admin API
  version: 1.0.0
  description: API for admin management

servers:
  - url: http://localhost:8080

paths:
  /admin:
    post:
      summary: Register a new admin
      description: Register a new admin with the provided details.
      operationId: registerAdmin
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AdminRegisterDTO"
      responses:
        "201":
          description: Admin successfully registered
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AdminDTO"
        "400":
          description: Invalid request data
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "409":
          description: Admin already exists
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /admin/{adminId}:
    get:
      summary: Get admin by ID
      operationId: getAdminById
      tags:
        - Admin
      parameters:
        - name: adminId
          in: path
          required: true
          description: Unique ID for every admin
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: Admin successfully retrieved
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AdminDTO"
        "404":
          description: Error retrieving admin data
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
    patch:
      summary: Update admin details
      operationId: updateAdmin
      tags:
        - Admin
      parameters:
        - name: adminId
          in: path
          required: true
          description: Unique ID for every admin
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AdminUpdateDTO"
      responses:
        "200":
          description: Admin updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AdminDTO"
        "404":
          description: No admin found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
    delete:
      summary: Delete admin
      operationId: deleteAdminById
      tags:
        - Admin
      parameters:
        - name: adminId
          in: path
          required: true
          description: Unique ID for every admin
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: Admin deleted successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AdminDTO"
        "404":
          description: Error deleting admin
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

components:
  schemas:
    AdminRegisterDTO:
      $ref: './schemas/adminRegisterDTO.yaml'
    AdminDTO:
      $ref: './schemas/adminDTO.yaml'
    AdminUpdateDTO:
      $ref: './schemas/adminUpdateRequestDTO.yaml'
    ErrorResponse:
      $ref: './schemas/errorResponse.yaml'
